### PR TITLE
added back button and image to RandomView

### PR DESCRIPTION
**Pull request by LimJames180**
Please Review

### CODE REVIEW

**Comment by Gabihkjvhrjkewh** [comment]
nice job!

**Comment by Gabihkjvhrjkewh** [comment]
could you consider making the window automatically go into fullscreen upon starting?

**Comment by callonlee** [comment]
No way u implemented this... You're genius! Pure genius!

**Comment by terence195** [comment]
what does load_recipe do?

**Comment by callonlee** [comment]
Dope 🔥

**Comment by LimJames180** [comment]
> could you consider making the window automatically go into fullscreen upon starting?

Sure thing, Time could be an issue though

**Comment by callonlee** [comment]
This is fire, abt to do backfilp 360

**Comment by terence195** [comment]
english or spanish

**Comment by LimJames180** [comment]
> 1 dollar or mystery commit

mystery commit

**Comment by Gabihkjvhrjkewh** [comment]
are we really putting this in the presentation

**Comment by LimJames180** [comment]
> english or spanish

No

**Comment by terence195** [comment]
> > what does load_recipe do?
> 
> It loads the 10 recipes at a time then iterates through the 10 before generating another 10, this reduces the api calls

Oh so it calls it from the controller inorder to show the recipes.

**Review by callonlee — APPROVED** [review]

**Comment by LimJames180** [comment]
> > > what does load_recipe do?
> > 
> > 
> > It loads the 10 recipes at a time then iterates through the 10 before generating another 10, this reduces the api calls
> 
> Oh so it calls it from the controller inorder to show the recipes.

yes then it uses the interactor to call in the entities

**Review by terence195 — APPROVED** [review]
Nice Clean Code keep up the good work

**Comment by Gabihkjvhrjkewh** [comment]
> > could you consider making the window automatically go into fullscreen upon starting?
> 
> Sure thing, Time could be an issue though

it's a rather simple change, you can refer to what the other view classes did!

**Pull request merged**
